### ISSUE TITLE
error while running simulation

### ISSUE THREAD

**Issue by AsimUdel** [lawrenceccheung/AWAKEN_summit_setup#2]
Hello @lawrenceccheung ,
I hope you are doing fine, I have some questions and problems while running the simulations.
1) I ran the Precursor and Turbine simulation while copying yours Neutral (Precursor and Turbine simulation, respectively), (Precursor https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/precursor/NeutralABL1/AMRWind/precursor_5x5_newWD.inp) and for turbine ( https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp), although these are for Neutral case I changed for the Stable case, 
[Turbine_Stable.txt](https://github.com/user-attachments/files/15889778/Turbine_Stable.txt)
[Stable_precursor.txt](https://github.com/user-attachments/files/15889780/Stable_precursor.txt)
I have some questions apologies, If I am asking basic or silly questions(does not the ending time of simulation in your turbine should be less than the Precursor? , and fixed_dt = 0.1 in turbine, but DT = 0.1 in OpenFAST .fst file, did not you get the error for that?

2) I have got an error while running the turbine simulation. after the precursor, due to time mismatch, I guess,
[Error_out.txt](https://github.com/user-attachments/files/15889821/Error_out.txt)

Thank you in advance

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

In answer to your first question, the precursor input file [precursor_5x5_newWD.inp](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/precursor/NeutralABL1/AMRWind/precursor_5x5_newWD.inp), that is not the final precursor run.  There was another precursor run after that which ran and collected the boundary data files, so the turbine run does not end after the precursor run.  Also, the OpenFAST timestep that we use is 0.01 (see [NREL-2p8-127.fst](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/turbines/OpenFAST3p3_NREL2p8-127.bugfix/NREL-2p8-127.fst)), which is 10 times the AMR-Wind timestep, so it should be okay.

The error message that you see here:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `(m_in_times[0] <= time) && (time < m_in_times.back())' failed, file "/work/archer/sw/rawcof_1/src/amr-wind/amr-wind/wind_energy/ABLBoundaryPlane.cpp", line 771
```
Means that the turbine simulation is requesting boundary plane data beyond the time period which it was captured, so it can't find the right data to use.

Lawrence

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung ,
Thank you so much for your response, I got it, and also by any chance do you have final precursor and turbine simulations run which you have used, I would be grateful if you could share those.

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

The final setup for the neutral precursor is available here: [precursor_5x5_newWD_restartwithPlanes.inp](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/precursor/NeutralABL1/AMRWind/precursor_5x5_newWD_restartwithPlanes.inp) -- this one includes the planes.

The final setup for the turbine run is already online at [5x5_newWD_withTurbine.inp](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp), it's the same one you mentioned before.

Lawrence

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung ,
Thank you so very much. Let me try these files with my settings for atmospheric stabilities and will get back to you if I got some errors.
Asim

**Comment by AsimUdel** [comment]
Hello @lawrenceccheung ,
I ran simulations using your input files as a reference, while modifying some parts. When I wanted to run turbine simulations I am getting "BodyForce.magnitude not found in table" error and it crashed, I noticed in your turbine simulation value of BodyForce.magnitude was not present, did you get that error too ?
[error_out.txt](https://github.com/user-attachments/files/15944999/error_out.txt)
[precursor_Neutral.txt](https://github.com/user-attachments/files/15945000/precursor_Neutral.txt)
[Turbine_Neutral.txt](https://github.com/user-attachments/files/15945001/Turbine_Neutral.txt)
Asim

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

It looks like in your run, you have specified that a `BodyForce` force be used, but did not specify `BodyForce.magnitude`.  In the error_out.txt file, I see the line
```
ICNS.source_terms(nvals = 5)  :: [BoussinesqBuoyancy, CoriolisForcing, ActuatorForcing, BodyForce, ABLMeanBoussinesq]
```
but of course, there is no `BodyForce.magnitude` specified.  However, Turbine_Neutral.txt does comment it out, so maybe there is some confusion about which input file is being used?

In our setup, we have used both `BodyForce` and `BodyForce.magnitude`.  You can find the relevant lines here:
https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp#L53
and
https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp#L78

Lawrence

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung,
thank you, my bad, actually I commented it out and tried to run after that error that's why there is confusion. [https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp#L78] (how did you calculate the BodyForce.magnitude ?

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung ,
Not related to the issue above, but regarding the tke calculations following your work "https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/post_processing/HH_profiles.ipynb" , can you please explain a bit ?
Does it mean total tke is calculated by summation of resolved and unresolved part ? and tke production is calculated by subtracting turbine to no turbine ? Thank you in advance
Asim

**Comment by lawrenceccheung** [comment]
> Hi @lawrenceccheung, thank you, my bad, actually I commented it out and tried to run after that error that's why there is confusion. [https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp#L78] (how did you calculate the BodyForce.magnitude ?

Hi @AsimUdel, I calculated the `BodyForce.magnitude` by time averaging the `abl_forcing_x` and `abl_forcing_y` variables that are in the ABL statistics file in the precursor.   I have a function in the amr-wind-frontend which does this, and also sets up a few other things for the restart.  You can see it in cell 8 of this notebook where I call `case.boundaryplane_restart()`:
https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/farmrun1_JRSE.ipynb

Lawrence

**Comment by lawrenceccheung** [comment]
> Hi @lawrenceccheung , Not related to the issue above, but regarding the tke calculations following your work "https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/post_processing/HH_profiles.ipynb" , can you please explain a bit ? Does it mean total tke is calculated by summation of resolved and unresolved part ? and tke production is calculated by subtracting turbine to no turbine ? Thank you in advance Asim

Yes, that's right.  I first calculated the mean flow-field and also the Reynolds stresses for the various sampling planes using this script here:
https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/post_processing/means/avgplanes.py
Then, to compute the resolved TKE, I did
```python
TKEres = 0.5*(hhds['uu_avg'][iplane,:,:] + hhds['vv_avg'][iplane,:,:] + hhds['ww_avg'][iplane,:,:])
```
in the [HH_profiles.ipynb](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/post_processing/HH_profiles.ipynb) notebook.  However, there's also a contribution of TKE coming from the subgrid scale model, so I added that to `TKEres` to get the total TKE:
```python
TKEsgs = hhds['tke_avg'][iplane,:,:]
TKEtot = TKEres + TKEsgs
```

You can repeat this calculation for the precursor planes as well, and then the difference in the total TKE between the two is the wake-added turbulence, as you were suggesting.

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung ,
Thank you so much. I got it. Just a quick question, it it better to take the difference between turbine and precursor or turbine and no turbine ? provided the boundary conditions (their periodicity) are different in precursor and turbine or no turbine case. 
Asim

**Comment by AsimUdel** [comment]
> > Hi @lawrenceccheung, thank you, my bad, actually I commented it out and tried to run after that error that's why there is confusion. [https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/NeutralABL_turbine1/AMR.5kmX5km_turbine1/5x5_newWD_withTurbine.inp#L78] (how did you calculate the BodyForce.magnitude ?
> 
> Hi @AsimUdel, I calculated the `BodyForce.magnitude` by time averaging the `abl_forcing_x` and `abl_forcing_y` variables that are in the ABL statistics file in the precursor. I have a function in the amr-wind-frontend which does this, and also sets up a few other things for the restart. You can see it in cell 8 of this notebook where I call `case.boundaryplane_restart()`: https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/NeutralABL_turbine1/AMR.5kmX5km_turbine1/farmrun1_JRSE.ipynb
> 
> Lawrence

Thank you so much

**Comment by lawrenceccheung** [comment]
> Hi @lawrenceccheung , Thank you so much. I got it. Just a quick question, it it better to take the difference between turbine and precursor or turbine and no turbine ? provided the boundary conditions (their periodicity) are different in precursor and turbine or no turbine case. Asim

This is good point.  Right now for wake-added turbulence statistics, we've been comparing against the "no-turbine" runs, where "no-turbine" means the exact same setup without any turbines in it -- so same mesh refinements, time-steps, etc.  That way any differences due to the numerics can be eliminated.

**Comment by AsimUdel** [comment]
Yes, Thank you @lawrenceccheung for your time and efforts.

**Comment by AsimUdel** [comment]
Hello @lawrenceccheung,
I have run simulation following your steps to run, (I made some changes, which are (I split precursor simulation and added spinup before that (with dt =0.5 dt and no mesh resolution in that),  reduced the domain size and some changes like in surface roughness, temperature etc). I have attached the input files, 
[spinup_unstable.txt](https://github.com/user-attachments/files/16057089/spinup_unstable.txt)
[precursor_unstable.txt](https://github.com/user-attachments/files/16057092/precursor_unstable.txt)
[Turbine_unstable.txt](https://github.com/user-attachments/files/16057095/Turbine_unstable.txt)
[No_turbine_unstable.txt](https://github.com/user-attachments/files/16057096/No_turbine_unstable.txt)

the xy plane velocity of spinup is 
![Spinup_hub_height_xy_unstable](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/5684d79e-94dc-4f59-83aa-b7b7349ab6af)

the xy plane velocity and tke plots of precursor simulation are
![Precursor_XY_hub_height](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/9dc9c102-9980-400f-a744-c16c14bc6336)
![Precusror_tke_xy](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/aed42285-88d5-4521-a939-9bc42f9487d0)

 I have got some problems
1) I have a feeling that, the inflow/outflows condition which are being saved after the precursor run are not saved properly and when those conditions are read in turbine simulation flow returns at (xhi, yhi and zhi) side. 
2) This problem has predominately appeared when I try to plot Avg TKE and vaguely appears in Avg velocity plots.
![Turbine_tke_xy](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/6d7caba4-d06d-4922-b458-a82c06481b63)
![Turbine_xy_plane](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/dc8ca5f7-c69a-4d57-9455-f9e13e86c0f9)

3)When I run the No_turbine simulation using (the same turbine simulation setting except suppressing the ActuatorForcing and Turbine input parameters), I also get the flow reversal behavior .
![No_Turbine_xy_plane](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/4ae74aa3-2f83-4a96-a04b-6ee5f7bf9f20)
![No_Turbine_tke_xy](https://github.com/lawrenceccheung/AWAKEN_summit_setup/assets/156853074/0c68a3f5-b04c-4f41-a8c0-3da7718e090d)


What do you suggest, what possibly I am doing wrong, should I avoid running Spinup simulation and only run Precursor? And what should I change in ABL.bndry_planes planes or any change in boundary conditions ? 
Thank you in advance for your time.
Asim

**Comment by lawrenceccheung** [comment]
hi @AsimUdel, my apologies for the delay in response.  I took a look at your setup and can suggest a couple of items.  First, the flow in the domain looks like it's predominately in the positive x-direction.  That's fine, but in the turbine run you have the following boundary conditions:
```
geometry.is_periodic                     = 0 0 0               
xlo.type                                 = mass_inflow         
xlo.density                              = 1.225             
xlo.temperature                          = 0.0                 
xlo.tke                                  = 0.0                 
xhi.type                                 = pressure_outflow    
ylo.type                                 = mass_inflow         
ylo.density                              = 1.225             
ylo.temperature                          = 0.0                 
ylo.tke                                  = 0.0                 
yhi.type                                 = pressure_outflow    
```
and the following boundary inflow planes:
```
ABL.bndry_planes                         = xlo ylo    
```
I don't believe the `ylo` boundary would actually have much inflow data to be fed into the domain -- the flow should be coming from the `xlo` face.  For the turbine run, I would suggest making the y-surfaces periodic:
```
geometry.is_periodic                     = 0 1 0               
```
and only applying boundary plane data on the `xlo` face.

Also, the initial temperature profile that's applied here:
```
ABL.temperature_heights                  = 0.0 90 600.0 700.0 1700.0    # Make sure the top height here goes above the domain height
ABL.temperature_values                   = 298 295.5 305.803 304.5 303.5
```
doesn't seem to have a capping inversion in the traditional sense.  The temperature gradient dT/dz as you approach `zhi` is negative, meaning that it's unstable in the upper part of the domain, and there isn't a means to kill the ABL turbulence as you approach the top of the domain.  I'm not sure if that's intentional, but could cause problems in the ABL later on.

Lawrence

**Comment by AsimUdel** [comment]
Thank you so much @lawrenceccheung , I have changed my input files after your suggestions and seems it is working fine. I have one more favor to ask, I am facing some problem while using Amr-Wind-Frontend " using Python recently, I used every time in the past, (when I want to start without GUI, recently I this error pops out every time)
![image](https://github.com/user-attachments/assets/4f0859c7-e966-48b5-8740-81a4321be8e3)

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel, yes, I can provide some help with that error message.  One minor organizational note -- could you post this problem and error message to https://github.com/Exawind/amr-wind-frontend/issues?  I can address it there.

Lawrence

**Comment by AsimUdel** [comment]
hi @lawrenceccheung , Thank you so much for your response, it was the issue in HPC's of University of Delaware (they revamped all the SSH connection and tunneling software) and not with the AMR-Wind-Frontend, IT department fixed it. I am closing this issue. 
Best Regards
Asim
